### PR TITLE
Central cp multi upfs - SPGW-C should not crash if unknown DP connects.

### PR DESCRIPTION
**Pull request by thakurajayL**
No need to exit the control plane if unknown DP connects to CP. Just log a message and ignore.

### CODE REVIEW

**Comment by thakurajayL** [comment]
> Will the code look better if we move the macro (lines 61-63) to one of the header files (maybe interface.h)? Or can we include a header file that already has this macro declared somewhere?

:) Yeah...it would be good if its part of some common file. I see that its part of nb.h, but then nb.h is included conditionally in interface.c.... Wondering if I should use direct logging API instead of using 
direct API instead of bringing in #define in between..

**Comment by thakurajayL** [comment]
Currently RTE_LOGTYPE_CP is defined in 10 files. Including the one which I added for this change.  Its defined in one of the file nb.h  but nb.h seems to be more than just logging. So placing this definition in the nb.h does not look good.  I don't see any suitable common place which can be included by all these 10 files... Creating common directory and then keeping common .h seems to be one of the option in front of me. Let me know your thoughts

**Comment by ajamshed** [comment]
How about keeping it in only `main.h`?

**Comment by thakurajayL** [comment]
> How about keeping it in only `main.h`?

Moved it to cp.h which was more suitable.

**Pull request merged**
