### PR TITLE
Add ability to resolve names in addition to IP

### PR DESCRIPTION
**Pull request by krsna1729**
Changed the function name from parse_arg_ip to parse_arg_host
Used getaddrinfo to be able to resolve names and dotted decimal IP
Duplication in DP is needed since interface.c is common

Fixes: #2

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
@micpez @suresh-marikkannu can you please take a look at the CI. Its failing in omec_tc2 c3po-mme https://jenkins.opencord.org/blue/organizations/jenkins/omec_tc2/detail/omec_tc2/19/pipeline/114/

This does not seem to be related

**Comment by micpez** [comment]
> 
> 
> @micpez @suresh-marikkannu can you please take a look at the CI. Its failing in omec_tc2 c3po-mme https://jenkins.opencord.org/blue/organizations/jenkins/omec_tc2/detail/omec_tc2/19/pipeline/114/
> 
> This does not seem to be related
Tracked in https://github.com/omec-project/omec-project-ci/issues/12

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Pull request merged**
