### PR TITLE
enable DDN on dp

### PR DESCRIPTION
**Pull request by pingping-lin**

### CODE REVIEW

**Comment by pingping-lin** [comment]
retest this please

**Comment by hyunsun** [comment]
retest this please

**Comment by pingping-lin** [comment]
retest this please

**Comment by pingping-lin** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Pull request merged**
