### PR TITLE
Move Makefile out of config folder

### PR DESCRIPTION
**Pull request by krsna1729**
Removed config/ng-core_cfg.mk
Added custom-{cp,dp}.mk files under cp/dp respectively
{cp,dp}/Makefile include local *.mk file

Partial: #4

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
ok to test

**Comment by krsna1729** [comment]
retest this please

**Comment by micpez** [comment]
This patch, along with #18, is needed to avoid configuration backup of makefiles in ngic-rtc cp/dp.
Resolve https://github.com/omec-project/omec-project-ci/issues/11

Manually tested successfully.

**Comment by cmaciocco** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
@cmaciocco please merge this. CI passed with changes from #64 and omec-project/omec-project-ci#11

**Comment by cmaciocco** [comment]
retest this please

**Pull request merged**
