### PR TITLE
Change Makefile to use standardized docker build method

### PR DESCRIPTION
**Pull request by hyunsun**

### CODE REVIEW

**Comment by krsna1729** [comment]
@hyunsun i think we need to add them to the Dockerfile also?

```
[Warning] One or more build-args [org_label_schema_vcs_ref org_label_schema_vcs_url org_label_schema_version org_opencord_vcs_commit_date org_label_schema_build_date] were not consumed
```

```
docker inspect ngic-dp:0.1.0-dev | grep -i label
            "Labels": null
            "Labels": null
```

**Comment by hyunsun** [comment]
@krsna1729 Done.

**Comment by hyunsun** [comment]
@krsna1729 Is it good to go?

**Comment by krsna1729** [comment]
@hyunsun yup

**Pull request merged**
