### PR TITLE
Make all kni scripts path-aware.

### PR DESCRIPTION
**Pull request by ajamshed**
Now one can run these scripts from any file location.

Signed-off-by: Muhammad Asim Jamshed <muhammad.jamshed@intel.com>

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by krsna1729** [comment]
ok to test

**Pull request merged**
