### PR TITLE
Allow ICMP for downlink

### PR DESCRIPTION
**Pull request by hyunsun**

### CODE REVIEW

**Comment by hyunsun** [comment]
Not sure if ICMP is disabled on purpose or not. If it's not, it would be good to allow it for test and development.

**Comment by krsna1729** [comment]
I think this was encountered previously.  @msewera @somnathchakrabarti @suresh-marikkannu can comment.

**Comment by suresh-marikkannu** [comment]
Hi, The below part of the code snippet will handle ICMP packets destined for SGI_IP (these packets will be send to kni for linux handling).

/* Flag pkt destined to SGI_IP for linux handling */
	if (app.sgi_ip == ho_addr)
	{
		RTE_LOG_DP(DEBUG, DP, "epc_dl.c:%s::"
				"\n\t@SGI:app.sgi_ip==ipv4_hdr->dst_addr= %s\n",
				__func__,
				inet_ntoa(*(struct in_addr *)&ho_addr));
		dl_arp_pkt = 1;
		return;
	}

NOTE: Sending ICMP packets to the fastpath processing will not be processed and it will be dropped (this comment is specific to the changed code in this PR).

**Comment by hyunsun** [comment]
Thanks. SGI port in my test was AF_PACKET mode and I guess that is why this PR worked.
Then I would think ICMP is not allowed except for SGI_IP.

**Comment by krsna1729** [comment]
@suresh-marikkannu are we blocking pings to UE intentionally?

**Comment by suresh-marikkannu** [comment]
@krsna1729 , no we are not blocking pings to UE. I think it should work.

**Comment by hyunsun** [comment]
@suresh-marikkannu Sorry but I think I'm not clear here, "_NOTE: Sending ICMP packets to the fastpath processing will not be processed and it will be dropped (this comment is specific to the changed code in this PR)._"
I'm not familiar with DPDK but my understanding is that spgwu doesn't need to process ICMP request but just forward it to the next hop. (I'm saying pining to external destination, not sgi_ip on spgwu) It looks like the current implementation doesn't allow this.

**Comment by suresh-marikkannu** [comment]
@hyunsun , Thanks for the details.  Sorry, i misunderstood the scenario earlier.

Yes your code change should allow UE ping now. However, we can update the code as follows (instead of checking each protocol, at this stage we can give all packets to fastpath processing,

    if (likely(ipv4_packet)) {
            RTE_LOG_DP(DEBUG, DP, "SGI packet\n");
            *port_id_offset = 0;
            dl_sgi_pkt = 1;
            dl_arp_pkt = 0;
    }

**Comment by krsna1729** [comment]
@hyunsun please make the change @suresh-marikkannu and test in your setup. I will merge it.

**Comment by hyunsun** [comment]
Thanks @suresh-marikkannu @krsna1729. The fix worked in my test.

**Pull request merged**
