### PR TITLE
Adding k8s manifests for cp and dp

### PR DESCRIPTION
**Pull request by krsna1729**
Adding kubernetes YAML files for CP and DP in SPGW-C/U mode
```
kubectl apply -f deploy/k8s
```
Fixes: #8 

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
Currently troubleshooting segfault on CP connecting
```
        0         0         0         0         0   ||         0         0         0         0         0
12: [/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f394ea6688f]]
11: [/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f394ed3d6db]]
10: [ngic_dataplane(eal_thread_loop+0x1f1) [0x5598082fc9f1]]
9: [ngic_dataplane(+0x81b91) [0x559808279b91]]
8: [ngic_dataplane(+0x81bbd) [0x559808279bbd]]
7: [ngic_dataplane(iface_process_ipc_msgs+0xdf) [0x55980828119f]]
6: [ngic_dataplane(+0x781b4) [0x5598082701b4]]
5: [ngic_dataplane(meter_profile_entry_add+0xb9) [0x559808280e29]]
4: [ngic_dataplane(dp_meter_profile_entry_add+0x2a) [0x55980827080a]]
3: [/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f394e983f20]]
2: [ngic_dataplane(sig_handler+0x38) [0x559808280568]]
1: [ngic_dataplane(rte_dump_stack+0x2e) [0x5598082fecae]]
EAL: Error - exiting with code: 1
  Cause: received SIGSEGV
```

**Comment by krsna1729** [comment]
`-O0 to -O2` seems fine. Issue seems to only appear with `-O3` and unrelated to this PR. So removing the do-not-merge

```
##NGCORE_SHRINK(RTC)
                  UPLINK                            ||                 DOWNLINK
IfMisPKTS    IfPKTS     UL-RX     UL-TX    UL-DFF   || IfMisPKTS    IfPKTS     DL-RX     DL-TX    DL-DFF
        0         0         0         0         0   ||         0         0         0         0         0
        0         0         0         0         0   ||         0         0         0         0         0
        0         0         0         0         0   ||         0         0         0         0         0
        0         0         0         0         0   ||         0         0         0         0         0
Logging MTR Records to ./cdr/mtr.csv
        0         0         0         0         0   ||         0         0         0         0         0
        0         0         0         0         0   ||         0         0         0         0         0
        0         0         0         0         0   ||         0         0         0         0         0
```

Will open a separate issue to track this.

**Comment by krsna1729** [comment]
@micpez @Sandeep-Sarma issue with openmme here too?
https://jenkins.opencord.org/job/omec_tc1/73/artifact/openmme/mme_app.stdout.log

**Comment by Sandeep-Sarma** [comment]
> @micpez @Sandeep-Sarma issue with openmme here too?
> https://jenkins.opencord.org/job/omec_tc1/73/artifact/openmme/mme_app.stdout.log

Issue was with Polaris load tester. We had to restart some of their services and it works now.

**Comment by krsna1729** [comment]
retest this please

**Pull request merged**
