### PR TITLE
fixed a typo in install.md. Created a PR to test trigger to Jenkins

### PR DESCRIPTION
**Pull request by Sandeep-Sarma**
…testing the job trigger at jenkins

### CODE REVIEW

**Comment by Sandeep-Sarma** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by Sandeep-Sarma** [comment]
retest this please

**Comment by Sandeep-Sarma** [comment]
retest this please

**Comment by Sandeep-Sarma** [comment]
retest this please

**Comment by Sandeep-Sarma** [comment]
retest this please

**Comment by krsna1729** [comment]
@Sandeep-Sarma @micpez is this testing done?

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Review by a-jamshed — APPROVED** [review]

**Review by krsna1729 — APPROVED** [review]

**Comment by ajamshed** [comment]
retest this please

**Pull request closed without merging**
