### PR TITLE
Add ngic config and install files in .ci dir

### PR DESCRIPTION
**Pull request by micpez**
Store configuration files and install files for CICD in .ci directory
in ngic-rtc repo, instead of having local configuration files on servers.

See https://github.com/omec-project/omec-project-ci/issues/21

### CODE REVIEW

**Comment by micpez** [comment]
cc @krsna1729 / @Sandeep-Sarma

**Comment by micpez** [comment]
retest this please

**Comment by krsna1729** [comment]
@micpez @suresh-marikkannu can we cleanup the config files to contain minimal options required? Also no need for copyright on config files I feel. If you still want to keep, convert to
```
; SPDX-License-Identifier: Apache-2.0
; Copyright(c) 2017 Intel Corporation
```

**Comment by krsna1729** [comment]
Also is it better to have config files per TC? That way its clear for users which settings are relevant in which test case

**Comment by micpez** [comment]
> Also is it better to have config files per TC? That way its clear for users which settings are relevant in which test case
Unless needed, I think it is better if everything is updated as soon as possible when installing,
The alternative is that the original version will be in place and would be wrong in any case.

**Comment by micpez** [comment]
@krsna1729 I moved config under tc1/tc2. Is it OK  like this or you have different view?
@Sandeep-Sarma , then we ca clean up files from unneeded rows.

**Comment by krsna1729** [comment]
Thanks @micpez for cleaning up the config files. Merging as per https://github.com/omec-project/omec-project-ci/pull/25#issuecomment-483123482

**Pull request merged**
