### PR TITLE
Fix EOL and whitespace

### PR DESCRIPTION
**Pull request by krsna1729**
Adding `.gitattributes` to enforce line endings to be LF.
Adding `trimWhitespace` filter to `.gitconfig` and reference in
`.gitattributes` to run git stripspace to remove all whitespace
automatically.

Developer will include the .gitconfig as follows

```bash
git config --local include.path ../.gitconfig
```

Running the below command processes all files git knows about as per the
.gitattributes and .gitconfig file

```bash
git rm --cached -r .
git reset --hard
```

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by krsna1729** [comment]
Needs more work closing for now

**Comment by krsna1729** [comment]
It was doing its job all along :P

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Comment by krsna1729** [comment]
retest this please

**Pull request merged**
